

#../Bin/User.o:
#	g++ User.cpp -c $^
#OBJDIR=../Bin

#$(OBJDIR)/%.o:

#../Bin/user.o: 
#	g++ User.cpp -c $^

OBJDIR=../Bin
#SRC_FILES := $(wildcard *.cpp)

#all: MakeFile



$(OBJDIR)/User.o:
	 g++ User.cpp -c -o $@ $^



